
public class AuraObject_TimedActivity {
    @AuraEnabled
    public  String recordId {get; set;}
    @AuraEnabled
    public  Datetime startDate {get; set;}
    @AuraEnabled
    public  Datetime endDate {get; set;}
    @AuraEnabled
    public  Boolean onTummy {get; set;}
    @AuraEnabled
    public  String comments {get; set;}
    @AuraEnabled
    public  String recordTypeName {get; set;}
    @AuraEnabled
    public  Boolean testing {get;set;}
}